### ISSUE TITLE
Replace pacaur

### ISSUE THREAD

**Issue by kalsan** [greyltc/docker-archlinux-aur#2]
As of December 2017, pacaur is unmaintained and will likely be broken by pacman 5.1, referring to https://bbs.archlinux.org/viewtopic.php?pid=1755144#p1755144

You might want to eventually switch to a different AUR helper: https://wiki.archlinux.org/index.php/AUR_helpers

Keep up the good work :-) :+1:

**Comment by greyltc** [comment]
apparently i've done this
