### ISSUE TITLE
yay too old?

### ISSUE THREAD

**Issue by xaratustrah** [greyltc/docker-archlinux-aur#4]
doing:

`RUN su docker -c 'yay -S --noprogressbar --needed --noconfirm PACKAGE'`

I get:

`yay: error while loading shared libraries: libalpm.so.11: cannot open shared object file: No such file or directory
`

possibly related to [this post](https://github.com/Jguer/yay/issues/1087).

New `yay` should solve the problem. Is it possible to trigger a new build on docker hub?

**Comment by greyltc** [comment]
the intent is for this to be re-built fortnightly. thanks for the heads up. I made some changes to the build triggers and so hopefully this issue is resolved and anything similar never comes up again.
