### ISSUE TITLE
"error: '*.pkg.tar': could not find or read package" after change to Zstandard for compression

### ISSUE THREAD

**Issue by PMunch** [greyltc/docker-archlinux-aur#5]
Had this error show up in a container I've been building with the add-aur script. Turns out it's because a lot of packages are switching to Zstandard for faster decompression speeds. This leads to them getting a new file extension. Changing https://github.com/greyltc/docker-archlinux-aur/blob/de94c439baf9fd393a5bb92aa566c6b5b8b765ec/add-aur.sh#L39 to install `.pkg.tar.zst` fixes the issue.

**Comment by greyltc** [comment]
Oh, thanks!

**Comment by greyltc** [comment]
all fixed!
